# Generated by Django 6.0.2 on 2026-02-12 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invenapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_qty', models.PositiveIntegerField(default=0)),
                ('low_stock_alert', models.PositiveIntegerField(default=5)),
                ('food_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='invenapp.fooditem')),
            ],
        ),
    ]
