# Generated by Django 6.0.2 on 2026-02-12 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invenapp', '0002_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('unit', models.CharField(max_length=20)),
                ('stock_qty', models.FloatField(default=0)),
                ('low_stock_alert', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.FloatField()),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='invenapp.fooditem')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invenapp.ingredient')),
            ],
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
