# Generated by Django 6.0.2 on 2026-02-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invenapp', '0004_wastage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('DINE_IN', 'Dine In'), ('TAKE_AWAY', 'Take Away')], max_length=20)),
                ('payment_mode', models.CharField(choices=[('COD', 'Cash On Delivery'), ('ONLINE', 'Online')], max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
